### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by ayk111** [RisingEdge19/STM32-PROFIBUS-Controller#1]
Добрый день, в
dev_config.dir = OUT;
dev_config.size = BYTE;
dev_config.len = 8;
задается конфигурация для модуля, а если в системе 2 модуля, к примеру 8 BYTE IN и 8 OUT.
Как отконфигурировать. Не могу понять.
Заранее спасибо.

**Comment by RisingEdge19** [comment]
Добрый день! В этом стеке не реализована возможность нескольких конфигурация, это же альфа) Я все-таки продолжил работу, но уже в коммерческом направлении... Могу только подсказать как в этот стек добавить такую возможность. Необходимо создать буфер конфигураций в hex и сравнить правильность и, главное, последовательность принятых байт конфигурации в телеграмме конфигурации при инициализации (конфиги будут лететь последовательно так, как вы их разместите в окне HW Config в step7). Запрос будет идти к устройству, а не к отдельному конфигу. Поэтому на основании конфига нужно будет указать какого типа будет слейв. Например, 8 Byte IN, 2 Byte IN, 3 Word IN > 16 Byte IN > SD1 телеграмма с PDU 16 байт. 7 Byte IN, 3 Byte OUT, 1 Byte OUT > INOUT > SD2 (REQ_PDU = 4  байта. RES_PDU: 7 байт). Как и конфиг, PDU будет лететь последовательно согласно конфигу. В сам же стек необходимо добавить сравнение буфера конфигураций и организовать правильный ответ в зависимости от этой суммарной конфгиурации. Можно указать непосредственно сам PDU и закинуть это в функцию, которая вернут массив конфигов и с ним уже сравнить. Либо опираться от конфига, заданного в хексе (как в степ7) и уже его распарсить > организовать необходимые ответы (SD2/SD1) с необходимым рамзеров PDU. В GSD нужно будет указать сколько конфигов (модулей) может иметь слейв. Как-то так... Я, кстати, перешел на другой контроллер, его на китае проще найти, к тому же есть оригиналы от WeAct Studio - STM32F411CEU6. у него 2 12.5МБит уарта, ДМА с двойным буфером, что делает его идеальным решением SW PROFIBUS контроллером интерфейса и связать его уже с контроллером верхнего уровня.

**Comment by ayk111** [comment]
Спасибо, разобрались, работает!
